name: JAR Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
#      - name: Check with Gradle
#        run: ./gradlew check
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
